version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      types:
        patterns:
          - "@types/*"
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
